# Generated by Django 5.2.7 on 2025-10-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='archivos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('instrumento', models.CharField(max_length=200)),
                ('tipo_calculo', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='nuam.emisor')),
            ],
        ),
    ]
