# Generated by Django 5.2.7 on 2025-11-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gastos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ArchivoCargado',
        ),
        migrations.DeleteModel(
            name='CalificacionTributaria',
        ),
        migrations.DeleteModel(
            name='Emisor',
        ),
    ]
