# Generated by Django 5.2.8 on 2025-11-17 14:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0002_registro_delete_archivocargado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='actualizado_en',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='creado_en',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='gastos',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='ingresos',
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='nota',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                default=0,  # 🔹 ANTES estaba timezone.now (mal), ahora 0 (ok)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='rut',
            field=models.CharField(
                max_length=12,
                default="0",  # 🔹 lo dejo como string por prolijidad
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se intentó acceder', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador o dispositivo desde donde se realizó el intento')),
                ('successful', models.BooleanField(help_text='¿El intento fue exitoso?')),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del intento')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario autenticado (si las credenciales fueron correctas)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
