# Generated by Django 5.2.8 on 2025-11-21 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0003_remove_registro_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='mercado',
            field=models.CharField(choices=[('ACCIONES', 'Acciones'), ('FONDOS', 'Fondos'), ('OTROS', 'Otros')], default='ACCIONES', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se hizo el intento', null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario autenticado (si el login fue exitoso)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Navegador / dispositivo'),
        ),
    ]
