# Generated by Django 5.2.8 on 2025-11-22 16:47

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0004_registro_mercado_alter_loginattempt_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Intento de inicio de sesión', 'verbose_name_plural': 'Intentos de inicio de sesión'},
        ),
        migrations.AlterModelOptions(
            name='registro',
            options={'ordering': ['-fecha_pago', '-fecha_creacion'], 'verbose_name': 'Registro de Calificación Tributaria', 'verbose_name_plural': 'Registros de Calificación Tributaria'},
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='rut',
        ),
        migrations.AddField(
            model_name='registro',
            name='calificacion_tributaria',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calificación tributaria entre 1.0 y 7.0.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción opcional del evento / instrumento.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='ejercicio',
            field=models.PositiveIntegerField(default=2023, help_text='Ejercicio / Año. Ej: 2023', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_10',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 10: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_11',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 11: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_12',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 12: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_13',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 13: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_14',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 14: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_15',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 15: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_16',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 16: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_17',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 17: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_18',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 18: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_19',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 19: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_20',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 20: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_21',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 21: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_22',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 22: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_23',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 23: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_24',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 24: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_25',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 25: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_26',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 26: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_27',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 27: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_28',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 28: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_29',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 29: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_30',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 30: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_31',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 31: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_32',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 32: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_33',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 33: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_34',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 34: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_35',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 35: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_36',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 36: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_37',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 37: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_8',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 8: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='factor_9',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 9: 1 entero y 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('9.99999999'))]),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_pago',
            field=models.DateField(default=datetime.date(2023, 1, 1), help_text='Fecha de pago en formato DD-MM-AAAA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='instrumento',
            field=models.CharField(default='TEMPORAL', help_text='Instrumento. Ej: COPEC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='numero_dividendo',
            field=models.CharField(blank=True, help_text='Número de dividendo (hasta 10 dígitos).', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El número de dividendo debe contener solo dígitos (máx. 10).', regex='^[0-9]{1,10}$')]),
        ),
        migrations.AddField(
            model_name='registro',
            name='secuencia_evento',
            field=models.CharField(default=1, help_text='Secuencia del evento (hasta 10 dígitos).', max_length=10, validators=[django.core.validators.RegexValidator(message='La secuencia debe contener solo dígitos (máx. 10).', regex='^[0-9]{1,10}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_sociedad',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', help_text='Tipo de sociedad: A = Abierta, C = Cerrada.', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='usuario_registro',
            field=models.ForeignKey(default=1, help_text='Usuario NUAM que realiza el ingreso o modificación.', on_delete=django.db.models.deletion.PROTECT, related_name='registros_calificacion', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='valor_historico',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Valor histórico (entero, hasta 10 dígitos).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='error_message',
            field=models.TextField(blank=True, help_text='Mensaje de error retornado (si aplica).'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP desde donde se hizo el intento.', null=True),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del intento.'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario autenticado (si el login fue exitoso).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Navegador / dispositivo del cliente.'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(help_text='Usuario ingresado en el formulario de login.', max_length=150),
        ),
        migrations.AlterField(
            model_name='registro',
            name='mercado',
            field=models.CharField(help_text='Mercado (3 caracteres). Ej: ACN', max_length=3, validators=[django.core.validators.RegexValidator(message='El mercado debe tener entre 1 y 3 caracteres en mayúscula.', regex='^[A-Z0-9]{1,3}$')]),
        ),
    ]
