# Generated by Django 5.2.8 on 2025-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0005_alter_loginattempt_options_alter_registro_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='tipo_sociedad',
            field=models.CharField(choices=[('SAA', 'Sociedad Anónima Abierta (S.A. Abierta)'), ('SAC', 'Sociedad Anónima Cerrada (S.A. Cerrada)'), ('SPA', 'Sociedad por Acciones (SpA)'), ('LTDA', 'Sociedad de Responsabilidad Limitada (Ltda.)'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada (EIRL)'), ('EXT', 'Sociedad Extranjera'), ('OTRA', 'Otra entidad / vehículo de inversión')], help_text='Tipo de sociedad emisora responsable del instrumento.', max_length=4),
        ),
    ]
