# Generated by Django 5.2.8 on 2025-11-25 17:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0006_alter_registro_tipo_sociedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='monto_evento_capital',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto monetario vinculado al evento de capital (por ejemplo, emisión, disminución o distribución de capital).', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto asociado al evento de capital'),
        ),
        migrations.AddField(
            model_name='registro',
            name='tipo_evento_capital',
            field=models.CharField(blank=True, choices=[('AUM_CAP', 'Aumento de capital'), ('DIS_CAP', 'Disminución de capital'), ('DIV_CAP', 'Distribución de dividendos'), ('FUSION', 'Fusión / Reorganización societaria'), ('OTRO', 'Otro evento de capital')], help_text='Clasificación del evento de capital asociado al instrumento.', max_length=20, null=True, verbose_name='Tipo de evento de capital'),
        ),
    ]
