# Generated by Django 5.2.8 on 2025-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0007_registro_monto_evento_capital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='isuf',
            field=models.BooleanField(default=False, help_text='Indica si la operación tiene tratamiento ISUF (Sí/No).'),
        ),
    ]
