# Generated by Django 5.2.8 on 2025-11-28 01:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuam', '0008_registro_isuf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='factor_10',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 10: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_11',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 11: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_12',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 12: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_13',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 13: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_14',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 14: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_15',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 15: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_16',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 16: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_17',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 17: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_18',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 18: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_19',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 19: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_20',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 20: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_21',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 21: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_22',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 22: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_23',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 23: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_24',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 24: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_25',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 25: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_26',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 26: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_27',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 27: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_28',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 28: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_29',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 29: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_30',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 30: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_31',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 31: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_32',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 32: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_33',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 33: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_34',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 34: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_35',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 35: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_36',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 36: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_37',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 37: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_8',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 8: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='factor_9',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Factor 9: decimal entre 0 y 1, con hasta 8 decimales.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1.00000000'))]),
        ),
    ]
